### ISSUE TITLE
Airline themes not working

### ISSUE THREAD

**Issue by mooreye** [akinomyoga/blesh-contrib#13]
On a fresh shell:

`bash --norc`

I only did `source ~/.local/share/blesh/ble.sh` to enable `blesh` and then I sourced solarized themed airline:

`source ~/.local/share/blesh/contrib/airline/solarized_flood.bash`

However, it doesn't actually look solarized, but like this:

https://i.imgur.com/OE66UsY.png

actually, any theme looks like this.

**Comment by akinomyoga** [comment]
The files inside `airline` are not intended to be directly sourced by users. Read [Manual §6.6.1](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A76-Vim-Mode#user-content-bleopt-vim_airline_theme).

**Comment by akinomyoga** [comment]
To be more explicit, you need to set it, for example, in the following way:

```bash
# blerc

function blerc/vim-load-hook {
  ble-import lib/vim-airline
  bleopt vim_airline_theme=solarized_flood
}
blehook/eval-after-load keymap_vi blerc/vim-load-hook
```

See also the setting in [`blerc.template`](https://github.com/akinomyoga/ble.sh/blob/3f31be186192b10e1c2c684accaf84a084a4b8c0/blerc.template#L1203).
