### ISSUE TITLE
fzf-git integration adding weird autocomplete suggestions

### ISSUE THREAD

**Issue by Dominiquini** [akinomyoga/blesh-contrib#17]
Enabling this integration (fzf-git) using:

```
_ble_contrib_fzf_git_config=key-binding:sabbrev:arpeggio
ble-import -d integration/fzf-git
```

This add strange suggestions for all the autocomplete commands. Every time, for every command that I press TAB, the options `[gf, ge, gb, gl, gh, gt, gr, gs]` appears on the list, on the bottom!
This bug appears to be fixed if I remove the line:

`_ble_contrib_fzf_git_config=key-binding:sabbrev:arpeggio`

I needed that line? For what? Everything appears to work fine without it!

Thanks.

**Comment by akinomyoga** [comment]
> `_ble_contrib_fzf_git_config=key-binding:sabbrev:arpeggio`
> 
> I needed that line?

It is described in [the last paragraph of the fzf-git section in README](https://github.com/akinomyoga/blesh-contrib#pencil-integrationfzf-git). That variable is a configuration that you can adjust. You need to pick the values that you would like to have.

> This add strange suggestions for all the autocomplete commands. Every time, for every command that I press TAB, the options `[gf, ge, gb, gl, gh, gt, gr, gs]` appears on the list, on the bottom!

This is not a bug. As described in README, if you include `sabbrev` in `_ble_contrib_fzf_git_config`, fzf-git defines sabbrev expansions (gf, ge, gb, gl, gh, gt, gr, gs) which can be used anywhere in the command line. Then, the completion system knows that they are possible keywords that can be expanded by the sabbrev expansion. If you don't use those sabbrev expansions, please just remove `sabbrev` from the colon-separated list `_ble_contrib_fzf_git_config`.
