### ISSUE TITLE
ble-face: face 'vim_airline_error_default' not found

### ISSUE THREAD

**Issue by alexalekseyenko** [akinomyoga/blesh-contrib#19]
Setting `vim_airline_theme=` to `minimalist`, `transparent`, `solarized`, or `monochrome` produces the following error on startup:
```
ble-face: face 'vim_airline_error_default' not found
```
Should the above themes be updated?

**Comment by akinomyoga** [comment]
Thanks for the report. I checked them. Those faces ending with `_default` should be removed. They are produced by [a bug in the auto-conversion](https://github.com/akinomyoga/ble.sh/blob/61968497add34548bc1ba6ba3516f813303d8391/memo/D1589-ConvertAirlineThemes.sh#L135-L136) of the theme files from the upstream vim-airline.

I'll fix them later. For the time being, you can remove the lines for `ble-face vim_airline_{error,term,warning}_default` in `contrib/airline/<theme name>.bash`.

**Comment by akinomyoga** [comment]
I fixed the script to generate the theme files (https://github.com/akinomyoga/ble.sh/commit/59787ee5528a8489e78ba09f712ed4b1f5a8e62f) and re-generated the theme files. I also added other theme files that I haven't included in the `master` branch of the `contrib` repository.

@alexalekseyenko Could you update ble.sh by running `ble-update` and check the behavior?

Note: If you've already edited the theme files in the `contrib` repository, please restore the original contents before attempting `ble-update` (To revert the changes, you can run e.g. `git reset --hard` inside the `contrib` directory.

**Comment by alexalekseyenko** [comment]
I can confirm that this has been fixed [even before I got a chance to try the workaround :D] --- thank you very much for creating and maintaining this awesome software!!

**Comment by akinomyoga** [comment]
Thank you for the confirmation!
