### ISSUE TITLE
fzf cd "alt-c" bug

### ISSUE THREAD

**Issue by markaacosta** [akinomyoga/blesh-contrib#21]
action: "alt-c" to `cd` into a directory via `fzf`

expected: `cd` into directory selected with `fzf`

actual: command is put on the line, but not *run*; to run it, user must press `backspace`, then press `enter`

Perhaps an extra newline is being added to the command output. If this carrage return / new line is not added to the output, it should `cd` correctly without requiring more action from the user

**Comment by akinomyoga** [comment]
That typically happens when one didn't follow [README](https://github.com/akinomyoga/ble.sh?tab=readme-ov-file#quick-instructions) (see the link to §2.8). Do you experience the problem after following README §2.8?

**Comment by markaacosta** [comment]
My mistake - I apparently commented my `ble-import` statements and was under the bad assumption I still had them. Everything is working fine

**Comment by akinomyoga** [comment]
Great. Can I close the issue?

**Comment by markaacosta** [comment]
Of course - thank you again!

**Comment by akinomyoga** [comment]
Thanks!
