### ISSUE TITLE
fzf integration does not work well with multiline prompts

### ISSUE THREAD

**Issue by SuperSandro2000** [akinomyoga/blesh-contrib#6]
I am using the powerline prompt design from sbp which is multline and has the cursor on line below it's usually place

![image](https://user-images.githubusercontent.com/7258858/150795076-fbd8ed87-5b4a-4b58-b374-2a8d521ecf1a.png)

Normally the fzf prompt looks like

![image](https://user-images.githubusercontent.com/7258858/150795035-3a735b0f-e55f-4d2e-8632-bc707b9c7d52.png)

![image](https://user-images.githubusercontent.com/7258858/150795620-25a9e485-f1f0-493b-b583-74f3b8a0c0c7.png)

but the ble.sh fzf integration moves it one up and overwrites the current prompt. When I close it the prompt comes back. I still did not read the entire documentation and do not know if there is a setting to easily fix this or this is a bug.

![image](https://user-images.githubusercontent.com/7258858/150795503-91118d91-bc9e-4e49-827e-60b06ada9332.png)

**Comment by SuperSandro2000** [comment]
Without ble.sh it looks like 

![image](https://user-images.githubusercontent.com/7258858/150795035-3a735b0f-e55f-4d2e-8632-bc707b9c7d52.png)

**Comment by akinomyoga** [comment]
Ah, OK. I think I misunderstood the issue. Also, I misunderstood which picture is the result with ble.sh and without ble.sh. Actually, the current behavior that `fzf` overwrites the entire current prompt has been somewhat expected by `ble.sh`, so I haven't regarded this behavior as an issue until now. Now, I have checked the behavior of GNU Readline and found that it actually changed its behavior between Bash 4.3 and 4.4. In Bash 4.4, it places the cursor at the end of the prompt (or equivalently the beginning of the command) before calling `fzf`. Until Bash 4.3, GNU Readline seems to place the cursor at the current editing position in the command line before calling `fzf`, which causes the problem that I initially assumed in my previous reply.

I'll fix the behavior to match it with GNU Readline.

**Comment by akinomyoga** [comment]
I have changed the behavior of ble.sh in commit https://github.com/akinomyoga/ble.sh/commit/7d05a28f9353bbb94376f8fecc8e6bfecaae3b42. Could you check the behavior?

**Comment by SuperSandro2000** [comment]
Thanks! Now it works like it did before.

**Comment by akinomyoga** [comment]
Thank you for checking the behavior! Can I close the issue now?
