### ISSUE TITLE
fzf integration - What is "_ble_contrib_fzf_base="?

### ISSUE THREAD

**Issue by Strykar** [akinomyoga/blesh-contrib#9]
What is this fzf directory that `_ble_contrib_fzf_base=` should point to according to the [README](https://github.com/akinomyoga/blesh-contrib#option-1-setup-in-fzfbash)?

This is what fzf installed on Arch Linux looks like:
```
$ pacq fzf
fzf /usr/
fzf /usr/bin/
fzf /usr/bin/fzf
fzf /usr/bin/fzf-tmux
fzf /usr/share/
fzf /usr/share/fish/
fzf /usr/share/fish/vendor_functions.d/
fzf /usr/share/fish/vendor_functions.d/fzf_key_bindings.fish
fzf /usr/share/fzf/
fzf /usr/share/fzf/completion.bash
fzf /usr/share/fzf/completion.zsh
fzf /usr/share/fzf/key-bindings.bash
fzf /usr/share/fzf/key-bindings.zsh
fzf /usr/share/licenses/
fzf /usr/share/licenses/fzf/
fzf /usr/share/licenses/fzf/LICENSE
fzf /usr/share/man/
fzf /usr/share/man/man1/
fzf /usr/share/man/man1/fzf-tmux.1.gz
fzf /usr/share/man/man1/fzf.1.gz
fzf /usr/share/vim/
fzf /usr/share/vim/vimfiles/
fzf /usr/share/vim/vimfiles/doc/
fzf /usr/share/vim/vimfiles/doc/fzf.txt
fzf /usr/share/vim/vimfiles/plugin/
fzf /usr/share/vim/vimfiles/plugin/fzf.vim
```
What should I set `_ble_contrib_fzf_base=`  to?

**Comment by akinomyoga** [comment]
Ah, this is a good question. You actually do not need to set `_ble_contrib_fzf_base` in this case and just run `ble-import`. `_ble_contrib_fzf_base` would be resolved automatically. But if you would like to specify it explicitly, it is [`/usr/share/fzf`](https://github.com/akinomyoga/blesh-contrib/blob/a2c0ee084d5eb144d543ff03a7530e9f7d306631/fzf-initialize.bash#L40). I think I need to later update README.

**Comment by Strykar** [comment]
Thank you!
Yes, that part in the README could do with some more clarification.

**Comment by akinomyoga** [comment]
I have updated `README.md` in commit bd823c97. Thank you!
